const techLogos = [
    { src: "/svgs/css.svg", alt: "CSS" },
    { src: "/svgs/git.svg", alt: "Git" },
    { src: "/svgs/html5.svg", alt: "HTML" },
    { src: "/svgs/mongodb.svg", alt: "MongoDB" },
    { src: "/svgs/nodejs.svg", alt: "Node" }, 
    { src: "/svgs/React.svg", alt: "React" },
    { src: "/svgs/postgresql.svg", alt: "PostgreSQL" },
    { src: "/svgs/Tailwind.svg", alt: "Tailwind" },
    { src: "/svgs/Bash.svg", alt: "Bash" },
    { src: "/svgs/bootstrap.svg", alt: "Bootstrap" },
    { src: "/svgs/dotenv.svg", alt: "Dotenv" },
    { src: "/svgs/Express.svg", alt: "Express" },
    { src: "/svgs/Github.svg", alt: "Github" },
    { src: "/svgs/javascript.svg", alt: "JavaScript" },
    { src: "/svgs/jest.svg", alt: "Jest" },
    { src: "/svgs/jQuery.svg", alt: "jQuery" },
    { src: "/svgs/json.svg", alt: "JSON" },
    { src: "/svgs/jwt.svg", alt: "JWT" },
    { src: "/svgs/Next.svg", alt: "NextJS" },
    { src: "/svgs/npm.svg", alt: "npm" },
    { src: "/svgs/sequelize.svg", alt: "Sequelize" },
    { src: "/svgs/stripe.svg", alt: "Stripe" },
    { src: "/svgs/svg.svg", alt: "svg" },
    { src: "/svgs/typescript.svg", alt: "TypeScript" },
    { src: "/svgs/Vercel.svg", alt: "Vercel" },
    { src: "/svgs/vitejs.svg", alt: "Vite" },
];

export default techLogos;
